apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: external-lb
spec:
  controller: hackclusterprivate-dns-989f708a.hcp.westus.azmk8s.io
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: external-lb
