# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: ""      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "OpenHackKeyVault120"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret        # object types: secret, key, or cert
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret        # object types: secret, key, or cert
    tenantId: "89093f41-f2fc-4852-822c-84a94b26a9be"           # The tenant ID of the key vault