apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: poi
  namespace: backend
spec:
  selector:
    matchLabels:
      app: poi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: poi
        tier: backend
    spec:
      containers:
      - name: poi
        image: registryhuz5030.azurecr.io/poi:latest  # or just image: redis
        resources:
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_USER 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_SERVER 
        - name: WEB_PORT
          value: "80"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Local"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi
    tier: backend
