apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: poi
  namespace: backend
spec:
  selector:
    matchLabels:
      app: poi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: poi
        tier: backend
    spec:
      containers:
      - name: poi
        image: registryhuz5030.azurecr.io/poi:latest  # or just image: redis
        resources:
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: WEB_PORT
          value: "80"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Local"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-system-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: backend
  labels:
    app: poi
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi
    tier: backend
