apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: tripviewer
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: tripviewer
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: tripviewer
        tier: frontend
    spec:
      containers:
      - name: tripviewer
        image: registryhuz5030.azurecr.io/tripviewer:latest  # or just image: redis
        resources:
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  selector:
    app: tripviewer
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer