apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      app: userprofile
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: userprofile
        tier: backend
    spec:
      containers:
      - name: userprofile
        image: registryhuz5030.azurecr.io/userprofile:latest  # or just image: redis
        resources:
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_USER 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: openhack
              key: SQL_SERVER 
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  labels:
    app: userprofile
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: userprofile
    tier: backend
